import { Command } from 'commander';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join, resolve } from 'path';
import { heading, success, info, icons, handleError, successBox, infoBox } from '../utils/ui.ts';

interface PlanAnswers {
  goal: string;
  files: string;
  constraints: string;
  noChange: string;
  done: string;
}

function generatePlanContent(answers: PlanAnswers): string {
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const timeStr = now.toTimeString().split(' ')[0];

  const lines: string[] = [];
  lines.push(`# Plan — ${dateStr}`);
  lines.push('');
  lines.push(`_Generated by \`omocs plan\` at ${dateStr} ${timeStr}_`);
  lines.push('');

  // Objective
  lines.push('## 🎯 Objective');
  lines.push('');
  lines.push(answers.goal);
  lines.push('');

  // Scope
  lines.push('## 📂 Scope');
  lines.push('');
  lines.push('### Files/Areas Involved');
  const filesList = answers.files.split(/[,\n]/).map(f => f.trim()).filter(Boolean);
  if (filesList.length > 0) {
    for (const f of filesList) {
      lines.push(`- ${f}`);
    }
  } else {
    lines.push('- _(not specified)_');
  }
  lines.push('');

  lines.push('### DO NOT Change');
  const noChangeList = answers.noChange.split(/[,\n]/).map(f => f.trim()).filter(Boolean);
  if (noChangeList.length > 0) {
    for (const item of noChangeList) {
      lines.push(`- ❌ ${item}`);
    }
  } else {
    lines.push('- _(no restrictions specified)_');
  }
  lines.push('');

  // Constraints
  lines.push('## ⚠️ Constraints & Requirements');
  lines.push('');
  const constraintsList = answers.constraints.split(/[,\n]/).map(f => f.trim()).filter(Boolean);
  if (constraintsList.length > 0) {
    for (const c of constraintsList) {
      lines.push(`- ${c}`);
    }
  } else {
    lines.push('- _(none specified)_');
  }
  lines.push('');

  // Steps (placeholder — to be filled by developer/agent)
  lines.push('## 📋 Steps');
  lines.push('');
  lines.push('_Break down the objective into atomic steps:_');
  lines.push('');
  lines.push('1. [ ] Research — understand current state');
  lines.push('2. [ ] Plan — define approach');
  lines.push('3. [ ] Implement — write the code');
  lines.push('4. [ ] Test — verify it works');
  lines.push('5. [ ] Review — check for edge cases');
  lines.push('');

  // Acceptance Criteria
  lines.push('## ✅ Definition of Done');
  lines.push('');
  const doneList = answers.done.split(/[,\n]/).map(f => f.trim()).filter(Boolean);
  if (doneList.length > 0) {
    for (const d of doneList) {
      lines.push(`- [ ] ${d}`);
    }
  } else {
    lines.push('- [ ] _(not specified)_');
  }
  lines.push('');

  // Risks
  lines.push('## 🚨 Risks');
  lines.push('');
  lines.push('_Potential issues to watch for:_');
  lines.push('');
  lines.push('- [ ] Breaking changes to existing functionality');
  lines.push('- [ ] Performance regression');
  lines.push('- [ ] Missing edge cases');
  lines.push('- [ ] Dependencies that need updating');
  lines.push('');

  // Notes
  lines.push('## 📝 Notes');
  lines.push('');
  lines.push('_(Add notes during implementation)_');
  lines.push('');

  return lines.join('\n');
}

export function registerPlanCommand(program: Command): void {
  program
    .command('plan')
    .description('Prometheus-style interview planner — structured planning before coding')
    .option('-o, --output <path>', 'Custom output path for the plan file')
    .option('--non-interactive', 'Skip interview, generate template only')
    .action(async (options: { output?: string; nonInteractive?: boolean }) => {
      try {
        heading('🔥 Prometheus Planner — Interview Mode');
        console.log(chalk.gray('  Answer these questions to create a structured plan.\n'));
        console.log(chalk.gray('  Tip: Use commas or newlines to separate multiple items.\n'));

        let answers: PlanAnswers;

        if (options.nonInteractive) {
          answers = {
            goal: 'TODO: Define the goal/task',
            files: 'TODO: List files/areas involved',
            constraints: 'TODO: List constraints or requirements',
            noChange: 'TODO: List things that should NOT be changed',
            done: 'TODO: Define what "done" looks like',
          };
        } else {
          answers = await inquirer.prompt([
            {
              type: 'editor',
              name: 'goal',
              message: '1/5 — What\'s the goal/task?',
              default: '',
              waitForUseInput: false,
            },
            {
              type: 'editor',
              name: 'files',
              message: '2/5 — What files/areas are involved?',
              default: '',
              waitForUseInput: false,
            },
            {
              type: 'editor',
              name: 'constraints',
              message: '3/5 — Any constraints or requirements?',
              default: '',
              waitForUseInput: false,
            },
            {
              type: 'editor',
              name: 'noChange',
              message: '4/5 — What should NOT be changed?',
              default: '',
              waitForUseInput: false,
            },
            {
              type: 'editor',
              name: 'done',
              message: '5/5 — Definition of done? (acceptance criteria)',
              default: '',
              waitForUseInput: false,
            },
          ]);
        }

        // Generate plan content
        const planContent = generatePlanContent(answers);

        // Determine output path
        const now = new Date();
        const pad = (n: number) => String(n).padStart(2, '0');
        const dateSlug = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}`;
        const defaultFileName = `plan-${dateSlug}.md`;

        let outputPath: string;
        if (options.output) {
          outputPath = resolve(options.output);
        } else {
          const plansDir = join(process.cwd(), '.opencode', 'plans');
          if (!existsSync(plansDir)) {
            mkdirSync(plansDir, { recursive: true });
          }
          outputPath = join(plansDir, defaultFileName);
        }

        // Ensure parent dir exists
        const parentDir = join(outputPath, '..');
        if (!existsSync(parentDir)) {
          mkdirSync(parentDir, { recursive: true });
        }

        writeFileSync(outputPath, planContent);

        console.log('');
        successBox('Plan Created', [
          `${chalk.gray('File:')} ${chalk.cyan(outputPath)}`,
          `${chalk.gray('Goal:')} ${answers.goal.split('\n')[0].slice(0, 60)}${answers.goal.length > 60 ? '...' : ''}`,
          '',
          `Edit the plan to refine steps and add details.`,
          `Use with: ${chalk.cyan('opencode --plan ' + outputPath)}`,
        ].join('\n'));

      } catch (error) {
        handleError(error);
      }
    });
}
