import { Command } from 'commander';
import chalk from 'chalk';
import { existsSync, readFileSync, writeFileSync, watchFile, unwatchFile, statSync, readdirSync, mkdirSync } from 'fs';
import { join, relative, basename, extname } from 'path';
import { createHash } from 'crypto';
import { heading, success, fail, warn, info, icons, handleError, infoBox, divider } from '../utils/ui.ts';

// ─── Constants ───────────────────────────────────────────────────────
const IGNORED_DIRS = ['node_modules', '.git', 'dist', 'build', '.next', '__pycache__', 'coverage', '.opencode', '.venv', 'vendor'];
const WATCHED_EXTS = ['.ts', '.tsx', '.js', '.jsx', '.py', '.go', '.rs', '.java', '.rb', '.php', '.vue', '.svelte', '.md'];
const AGENTS_FILE = 'AGENTS.md';

// ─── Helpers ─────────────────────────────────────────────────────────
interface DirInfo {
  path: string;
  name: string;
  files: string[];
  subdirs: string[];
  depth: number;
}

function scanDirectory(dir: string, maxDepth: number = 3, currentDepth: number = 0): DirInfo[] {
  const results: DirInfo[] = [];

  if (currentDepth > maxDepth) return results;
  if (!existsSync(dir)) return results;

  try {
    const entries = readdirSync(dir, { withFileTypes: true });
    const files: string[] = [];
    const subdirs: string[] = [];

    for (const entry of entries) {
      if (entry.name.startsWith('.') && entry.name !== '.opencode') continue;
      if (IGNORED_DIRS.includes(entry.name)) continue;

      if (entry.isDirectory()) {
        subdirs.push(entry.name);
      } else if (entry.isFile() && WATCHED_EXTS.includes(extname(entry.name))) {
        files.push(entry.name);
      }
    }

    if (files.length > 0 || subdirs.length > 0) {
      results.push({
        path: dir,
        name: basename(dir),
        files,
        subdirs,
        depth: currentDepth,
      });
    }

    for (const subdir of subdirs) {
      results.push(...scanDirectory(join(dir, subdir), maxDepth, currentDepth + 1));
    }
  } catch { /* skip unreadable */ }

  return results;
}

function generateStructureHash(dirs: DirInfo[]): string {
  const data = dirs.map(d => `${d.path}:${d.files.join(',')}:${d.subdirs.join(',')}`).join('|');
  return createHash('sha256').update(data).digest('hex').substring(0, 16);
}

function generateAgentsMd(rootDir: string, dirs: DirInfo[]): string {
  const projectName = basename(rootDir);
  const lines: string[] = [];

  lines.push(`# AGENTS.md — ${projectName}`);
  lines.push('');
  lines.push('> Auto-generated by `omocs watch`. Edit sections marked as safe to customize.');
  lines.push('');
  lines.push('## Project Structure');
  lines.push('');
  lines.push('```');

  // Build tree
  for (const dir of dirs) {
    const rel = relative(rootDir, dir.path) || '.';
    const indent = '  '.repeat(dir.depth);
    const dirLabel = dir.depth === 0 ? projectName + '/' : dir.name + '/';
    lines.push(`${indent}${dirLabel}`);

    for (const file of dir.files.slice(0, 15)) {
      lines.push(`${indent}  ${file}`);
    }
    if (dir.files.length > 15) {
      lines.push(`${indent}  ... (${dir.files.length - 15} more files)`);
    }
  }

  lines.push('```');
  lines.push('');

  // Tech detection
  lines.push('## Tech Stack (Auto-detected)');
  lines.push('');

  const allFiles = dirs.flatMap(d => d.files);
  const fileSet = new Set(allFiles.map(f => extname(f)));
  const dirNames = dirs.map(d => d.name);

  if (fileSet.has('.ts') || fileSet.has('.tsx')) lines.push('- **TypeScript**');
  if (fileSet.has('.js') || fileSet.has('.jsx')) lines.push('- **JavaScript**');
  if (fileSet.has('.py')) lines.push('- **Python**');
  if (fileSet.has('.go')) lines.push('- **Go**');
  if (fileSet.has('.rs')) lines.push('- **Rust**');
  if (fileSet.has('.java')) lines.push('- **Java**');
  if (fileSet.has('.rb')) lines.push('- **Ruby**');
  if (fileSet.has('.vue')) lines.push('- **Vue.js**');
  if (fileSet.has('.svelte')) lines.push('- **Svelte**');

  // Framework detection
  if (existsSync(join(rootDir, 'next.config.js')) || existsSync(join(rootDir, 'next.config.ts')) || existsSync(join(rootDir, 'next.config.mjs'))) {
    lines.push('- **Next.js**');
  }
  if (existsSync(join(rootDir, 'nest-cli.json')) || allFiles.some(f => f.includes('.module.ts'))) {
    lines.push('- **NestJS**');
  }
  if (existsSync(join(rootDir, 'package.json'))) lines.push('- **Node.js**');
  if (existsSync(join(rootDir, 'docker-compose.yml')) || existsSync(join(rootDir, 'docker-compose.yaml'))) {
    lines.push('- **Docker Compose**');
  }
  if (existsSync(join(rootDir, 'Dockerfile'))) lines.push('- **Docker**');
  if (existsSync(join(rootDir, 'Cargo.toml'))) lines.push('- **Cargo**');
  if (existsSync(join(rootDir, 'go.mod'))) lines.push('- **Go Modules**');
  if (existsSync(join(rootDir, 'pyproject.toml')) || existsSync(join(rootDir, 'requirements.txt'))) {
    lines.push('- **pip/Poetry**');
  }

  lines.push('');

  // Key directories
  lines.push('## Key Directories');
  lines.push('');

  for (const dir of dirs.filter(d => d.depth <= 1)) {
    const rel = relative(rootDir, dir.path) || '.';
    const fileCount = dir.files.length;
    const purpose = inferDirPurpose(dir.name, dir.files);
    lines.push(`- **\`${rel}/\`** — ${purpose} (${fileCount} files)`);
  }

  lines.push('');
  lines.push('## Custom Instructions');
  lines.push('');
  lines.push('<!-- SAFE TO EDIT: Add your custom agent instructions below -->');
  lines.push('');
  lines.push('_(Add project-specific instructions here. This section is preserved on regeneration.)_');
  lines.push('');

  return lines.join('\n');
}

function inferDirPurpose(name: string, files: string[]): string {
  const lower = name.toLowerCase();
  if (lower === 'src' || lower === 'lib') return 'Source code';
  if (lower === 'test' || lower === 'tests' || lower === '__tests__') return 'Test files';
  if (lower === 'components') return 'UI Components';
  if (lower === 'pages' || lower === 'app') return 'Pages/Routes';
  if (lower === 'api') return 'API endpoints';
  if (lower === 'utils' || lower === 'helpers') return 'Utilities';
  if (lower === 'hooks') return 'React hooks';
  if (lower === 'styles' || lower === 'css') return 'Stylesheets';
  if (lower === 'public' || lower === 'static' || lower === 'assets') return 'Static assets';
  if (lower === 'config' || lower === 'configs') return 'Configuration';
  if (lower === 'scripts') return 'Build/utility scripts';
  if (lower === 'docs' || lower === 'documentation') return 'Documentation';
  if (lower === 'migrations') return 'Database migrations';
  if (lower === 'types') return 'Type definitions';
  if (lower === 'services') return 'Service layer';
  if (lower === 'controllers') return 'Controllers';
  if (lower === 'models' || lower === 'entities') return 'Data models';
  if (lower === 'middleware') return 'Middleware';
  if (lower === 'guards') return 'Auth guards';
  if (lower === 'dto' || lower === 'dtos') return 'Data transfer objects';
  return 'Project directory';
}

// ─── Register Command ────────────────────────────────────────────────
export function registerWatchCommand(program: Command): void {
  const watch = program
    .command('watch')
    .description('Watch project structure and auto-regenerate AGENTS.md');

  // watch start
  watch
    .command('start')
    .description('Start watching for file structure changes')
    .option('--interval <seconds>', 'Check interval in seconds', '30')
    .option('--depth <n>', 'Max directory depth to scan', '3')
    .option('--dry-run', 'Show what would be generated without writing')
    .action((opts) => {
      try {
        const rootDir = process.cwd();
        const depth = parseInt(opts.depth) || 3;
        const interval = (parseInt(opts.interval) || 30) * 1000;

        heading('👁️ Watch Mode');
        info(`Watching: ${chalk.cyan(rootDir)}`);
        info(`Depth: ${depth} | Interval: ${interval / 1000}s`);
        console.log('');

        let lastHash = '';

        const checkAndUpdate = () => {
          const dirs = scanDirectory(rootDir, depth);
          const hash = generateStructureHash(dirs);

          if (hash !== lastHash) {
            if (lastHash !== '') {
              info(`Structure change detected at ${new Date().toLocaleTimeString()}`);
            }

            const content = generateAgentsMd(rootDir, dirs);

            if (opts.dryRun) {
              console.log(chalk.gray('\n--- Generated AGENTS.md preview ---'));
              console.log(content);
              console.log(chalk.gray('--- End preview ---\n'));
            } else {
              // Preserve custom sections
              const agentsPath = join(rootDir, AGENTS_FILE);
              if (existsSync(agentsPath)) {
                const existing = readFileSync(agentsPath, 'utf-8');
                const customMatch = existing.match(/## Custom Instructions[\s\S]*$/);
                if (customMatch) {
                  const newContent = content.replace(/## Custom Instructions[\s\S]*$/, customMatch[0]);
                  writeFileSync(agentsPath, newContent, 'utf-8');
                } else {
                  writeFileSync(agentsPath, content, 'utf-8');
                }
              } else {
                writeFileSync(agentsPath, content, 'utf-8');
              }

              if (lastHash !== '') {
                success(`AGENTS.md updated (${dirs.length} dirs, hash ${hash})`);
              } else {
                success(`AGENTS.md generated (${dirs.length} dirs)`);
              }
            }

            lastHash = hash;
          }
        };

        // Initial check
        checkAndUpdate();

        // Poll mode
        info(`Watching for changes... (Ctrl+C to stop)`);
        const timer = setInterval(checkAndUpdate, interval);

        process.on('SIGINT', () => {
          clearInterval(timer);
          console.log('');
          info('Watch stopped.');
          process.exit(0);
        });
      } catch (err) { handleError(err); }
    });

  // watch generate (one-shot)
  watch
    .command('generate')
    .alias('gen')
    .description('Generate AGENTS.md once (no watching)')
    .option('--depth <n>', 'Max directory depth', '3')
    .option('--output <file>', 'Output file path', AGENTS_FILE)
    .option('--preserve-custom', 'Keep existing Custom Instructions section', true)
    .action((opts) => {
      try {
        const rootDir = process.cwd();
        const depth = parseInt(opts.depth) || 3;

        heading('📄 Generate AGENTS.md');

        const dirs = scanDirectory(rootDir, depth);
        const content = generateAgentsMd(rootDir, dirs);

        const outputPath = join(rootDir, opts.output);

        // Preserve custom sections
        if (opts.preserveCustom && existsSync(outputPath)) {
          const existing = readFileSync(outputPath, 'utf-8');
          const customMatch = existing.match(/## Custom Instructions[\s\S]*$/);
          if (customMatch) {
            const newContent = content.replace(/## Custom Instructions[\s\S]*$/, customMatch[0]);
            writeFileSync(outputPath, newContent, 'utf-8');
            success(`AGENTS.md regenerated (custom section preserved)`);
            return;
          }
        }

        writeFileSync(outputPath, content, 'utf-8');
        success(`Generated ${chalk.cyan(opts.output)} — ${dirs.length} directories scanned`);

        // Stats
        const allFiles = dirs.flatMap(d => d.files);
        info(`Files tracked: ${allFiles.length}`);
        info(`Directories: ${dirs.length}`);
      } catch (err) { handleError(err); }
    });

  // Default: generate once
  watch.action(() => {
    heading('👁️ AGENTS.md Auto-Sync');
    infoBox('Watch', [
      'Auto-generate and sync AGENTS.md with project structure.',
      '',
      `  ${chalk.cyan('omocs watch start')}       — watch for changes`,
      `  ${chalk.cyan('omocs watch generate')}    — one-shot generation`,
      '',
      'Custom Instructions section is always preserved.',
    ].join('\n'));
  });
}
